### ISSUE TITLE
Character count of selection is very wrong

### ISSUE THREAD

**Issue by wdscxsj** [Emurasoft/CharacterCount#2]
![](https://i.postimg.cc/GmtWXCjL/Screenshot027.png)

Update 1: Tested again and I think it's caused by setting "Newline" as "1 character". The count somehow includes **all** newlines in the document.

Update 2: In `count.cpp`, if selection is not empty, `counts[logicalLines]` and `counts[viewLines]` should be calculated based on the selected text.

**Comment by MakotoE** [comment]
Thanks for the report. This is not a bug; this is intentional. In the documentation, it says:

> * Logical lines - Number of lines in file
> * View lines - Number of lines shown in editor

With that said, I do think this is was a really bad design choice and I'm not sure what I was thinking. Considering that the program outputs the number of CR/LF newline characters in selection, I will not change the interface or behavior.

**Comment by wdscxsj** [comment]
Thanks for the response, but I do think this is a bug.

First of all, why "Characters" is 6 when the selection is obviously 1?

The inconsistency between the UI and the documentation doesn't mean "by original design" is correct and proper. There is no need to go into the documentation if the UI says enough, right?

IIRC, CharacterCount was meant to replace the 32-bit only (and no longer maintained?) Text Information plug-in by KKSoftWare. That's exactly what I need, and Text Information behaves quite well with selected text, treating any kind of EOL as 1 character. It's a pity to lose compatibility in such a surprising way.

**Comment by MakotoE** [comment]
I apologize for completely missing the part about the incorrect character count. Now, line count and character count shows what it should—line and character counts within the current selection.

Though character count should have added lines within the selection, it mistakenly used the whole document line count—because of the fact that the line count was for the entire document regardless of selection status. https://github.com/Emurasoft/CharacterCount https://github.com/Emurasoft/CharacterCount/blob/4e6cc0e586912b912c74e3b5648464211477a094/count.cpp#L292-L295

I'm going to clean up the code and do a bit more testing before I build version 2.

**Comment by wdscxsj** [comment]
Hi, thanks for the update! The <del>character count and</del> line counts of selected text look good now, but the control character count is incorrect. With the following setting, it should be 3, same as the number of selected LF characters:

![](https://i.postimg.cc/xC5c1m5b/Screenshot028.png)

LF-style and CR-style files have the same issue, but not CRLF-style files. With a little investigation, it seems that when copying out the selected text, **multiple zero (NULL) characters sneak into end of the buffer**, and are later counted as control characters. The count is equal to the number of selected newlines.

Update 1: Just noticed that the characters count is also incorrect. It's not stable, either. Invoking CharacterCount multiple times with the same selection, occasionally I got 17 or 18:

![](https://i.postimg.cc/xCpNPHmV/Screenshot029.png)

I guess all these issues are caused by the extra trailing NULL characters.

**Comment by wdscxsj** [comment]
Hi, I think the fix is working now. It'll be better if this can be solved upstream. Please feel free to close this issue after all your tests. Thanks a lot for the hard work!

**Comment by MakotoE** [comment]
Sorry, what do you mean by "It'll be better if this can be solved upstream."?

I just compiled the plugin. Thank you for reporting the issue.

**Comment by wdscxsj** [comment]
Hi, I mean it'll be better if `Editor_GetSelTextW` (and other similar APIs) returns a buffer of exactly one trailing NULL character, like a conventional C string. This is not promised in the EmEditor Help, and I just think it'll be better if it does so in practice.

**Comment by MakotoE** [comment]
Yes, I agree. In fact, the `Editor_GetLineW` function returns what I expect for \n unlike `Editor_GetSelTextW`. I will let Yutaka know.
